---
- name: Install Apache
  hosts: app
  become: true

  handlers:
   - name: restart apache
     service: 
       name: httpd
       state: restarted
  tasks: 
   - name: install
     yum:
       name: httpd
       state: present
   - name: copy config file.
     copy:
       src: /etc/ansible/playbooks/apache-config.yml
       dest: /var/www/html/index.html
     notify: restart apache

   - name: start & enable
     service: 
       name: httpd
       state: started
       enabled: yes     
